apiVersion: v2
name: PreDeployment
description: Pre-Deployment components for Kubernetes Cluster
type: application
version: 0.1.0
appVersion: "1.16.0"
dependencies:
  - name: cert-manager
    version: "v1.9.1"
    repository: https://charts.jetstack.io
    alias: cert-manager
    condition: cert-manager.enabled
    tags:
      - cert-manager
  - name: external-dns
    version: "6.8.1"
    repository: https://charts.bitnami.com/bitnami
    alias: external-dns
    condition: external-dns.enabled
    tags:
      - external-dns
  - name: ingress-nginx
    version: "2.3.0"
    repository: https://kubernetes.github.io/ingress-nginx
    alias: ingress-nginx
    condition: ingress-nginx.enabled
    tags:
      - ingress-nginx